//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public long Id { get; set; }
        public string Category { get; set; }
        public string Deadline { get; set; }
        public string Priority { get; set; }
        public Nullable<decimal> EstimatedTime { get; set; }
        public string TaskName { get; set; }
    }
}
